Add bookings
veronyurova/java-shareit pull request #2
Opened 2022-07-22 11:10 UTC by veronyurova

Настроила PostgreSQL БД для проекта, создала схему.
Добавила в проект JPA, настроила старый функционал (Users и Items) для работы с JPA.
Также был реализован новый функционал - бронирования и отзывы.

2022-07-23 10:53 UTC, kukolev requested changes

2022-07-23 10:53 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        return BookingMapper.toBookingDto(bookingService.updateBookingStatus(userId, bookingId,
Маппинг ДТО это тоже часть логики, которая должна быть реализована в сервисе. Нужно перенести маппинг в сервис.

2022-07-23 10:53 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    List<Booking> findAllByBookerIdAndStartIsBeforeAndEndIsAfterOrderByStartDesc(Long userId,
По моему такие методы очень плохо читаются в коде. Будет лучше, если названия будут короткими, а логика поиска будет реализована в `@Query`

2022-07-23 10:53 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/Comment.java
> +    Long id;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-07-23 10:53 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/CommentDto.java
> +    Long id;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-07-23 10:53 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            bookingState = BookingState.valueOf(state);
Маппинг и валидация входных данных это логика, которая должна быть реализована в сервисе. Нужно перенести этот код в сервис.

Аналогично нужно поправить в других методах ниже.

2022-07-24 10:06 UTC, veronyurova commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        return BookingMapper.toBookingDto(bookingService.updateBookingStatus(userId, bookingId,
Переработала архитектуру - теперь маппинг DTO и валидация проходят в сервисах.

2022-07-24 10:06 UTC, veronyurova commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            bookingState = BookingState.valueOf(state);
Переработала архитектуру - теперь маппинг DTO и валидация проходят в сервисах.

2022-07-24 10:06 UTC, veronyurova commented on src/main/java/ru/practicum/shareit/item/CommentDto.java
> +    Long id;
Поправила.

2022-07-24 10:07 UTC, veronyurova commented on src/main/java/ru/practicum/shareit/item/Comment.java
> +    Long id;
Поправила.

2022-07-24 10:08 UTC, veronyurova commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    List<Booking> findAllByBookerIdAndStartIsBeforeAndEndIsAfterOrderByStartDesc(Long userId,
Заменила использование нечитаемых запросных методов на использование аннотаций @Query.

2022-07-24 17:24 UTC, kukolev requested changes

2022-07-24 17:24 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +@Slf4j
Сейчас эта аннотация здесь не нужна, т.к. логи не выводятся. Нужно или убрать аннотацию или добавить логи.

2022-07-24 17:24 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public BookingDto updateBookingStatus(Long userId, Long bookingId, Boolean approved) {
По моему этот метод лучше разбить на два - сначала сделать валидацию, а потом уже логику. Так метод будет проще читаться.

2022-07-24 17:24 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public BookingDto addBooking(Long userId, Long itemId, @Valid BookingDtoAdd bookingDtoAdd) {
По моему этот метод лучше разбить на два - сначала сделать валидацию, а потом уже логику. Так метод будет проще читаться.

2022-07-24 17:24 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemDto.java
> +    private Booking lastBooking;
По моему здесь должно быть BookingDto вместо Booking. ДТО могут содержать другие ДТО в полях, но никак не сущности.

2022-07-24 20:20 UTC, veronyurova commented on src/main/java/ru/practicum/shareit/item/ItemDto.java
> +    private Booking lastBooking;
Поправила наименования DTO (раньше внутренние DTO неправильно назывались, из-за чего было непонятно, что используется DTO, а не сама сущность)

2022-07-24 20:21 UTC, veronyurova commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +@Slf4j
Убрала лишнюю аннотацию.

2022-07-24 20:22 UTC, veronyurova commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public BookingDto updateBookingStatus(Long userId, Long bookingId, Boolean approved) {
Вынесла валидацию в отдельный приватный метод.

2022-07-24 20:22 UTC, veronyurova commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public BookingDto addBooking(Long userId, Long itemId, @Valid BookingDtoAdd bookingDtoAdd) {
Вынесла валидацию в отдельный приватный метод.

2022-07-25 07:41 UTC, kukolev approved these changes

2022-07-31 11:00 UTC, merged