Add item requests
veronyurova/java-shareit pull request #3
Opened 2022-08-06 11:01 UTC by veronyurova

В приложение добавлена новая функциональность - запрос вещи. Также добавлена возможность отвечать на запросы.
Во все get-методы, которые возвращают много данных была добавлена пагинация. 

Приложение было покрыто:
- юнит-тестами для сервисов с использованием моков
- тестами для контроллеров с использованием MockMVC
- тестами для репозиториев с использованием аннотации @DataJpaTest
- интеграционными тестами для основных методов сервисов
- JSON-тестами для сложных DTO

2022-08-06 17:46 UTC, kukolev requested changes

2022-08-06 17:46 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            Optional<ItemRequest> request = itemRequestRepository.findById(requestId);
По моему здесь лучше воспользоваться .ifPresent и там уже в лямбде прописать присвоение реквеста. Так код будет проще.

2022-08-06 18:56 UTC, veronyurova commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            Optional<ItemRequest> request = itemRequestRepository.findById(requestId);
Заменила лишнее условие на `.ifPresent`. Также заменила условие на `.ifPresent` в методе addLastAndNextBooking.

2022-08-07 08:42 UTC, kukolev approved these changes

2022-08-07 09:05 UTC, merged