Add docker
veronyurova/java-shareit pull request #4
Opened 2022-08-17 19:53 UTC by veronyurova

2022-08-18 16:20 UTC, kukolev requested changes

2022-08-18 16:20 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        try {
Бизнес-логика должна быть реализована в сервисах, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

Аналогично нужно поправить ниже.

2022-08-18 16:20 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        BookingState bookingState;
Бизнес-логика должна быть реализована в сервисах, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

Аналогично нужно поправить ниже.

2022-08-18 18:46 UTC, veronyurova commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        try {
Поправила - перенесла связанную с BookingState логику из контроллера в сервис.

2022-08-18 18:47 UTC, veronyurova commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        BookingState bookingState;
Поправила - перенесла связанную с BookingState логику из контроллера в сервис.

2022-08-19 05:41 UTC, kukolev requested changes

2022-08-19 05:41 UTC, kukolev commented on server/src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        try {
Этот блок кода практически повторяет аналогичный выше. Такой код нужно упростить - вынести в отдельный приватный метод.

2022-08-19 05:41 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +                        Object.class, parameters);
По моему этот перенос строки смотрится лишним. На предыдущей строке есть место. Код будет смотреться лучше без переноса.

2022-08-19 08:41 UTC, veronyurova commented on server/src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        try {
Убрала дублирование кода - вынесла логику, связанную с конвертированием в BookingState в приватный метод.

2022-08-19 08:41 UTC, veronyurova commented on gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +                        Object.class, parameters);
Убрала лишний перенос.

2022-08-19 20:35 UTC, kukolev approved these changes

2022-08-20 10:42 UTC, merged